version: "3.8" # Docker Compose version

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes:
      - ./server:/app # Sync code between host and container
    environment:
      - NODE_ENV=development
    command: npm start # Run the server in development mode

  client:
    build:
      context: ./client
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    command: npm run dev # Run the client in development mode

  model_service:
    build:
      context: ./model # Path to your Python model folder
      dockerfile: Dockerfile
    volumes:
      - ./model:/app
    ports:
      - "5001:5000" # Expose port for the model API
    environment:
      - FLASK_ENV=development # Or any other necessary environment variables
