version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - model_service
    volumes:
      - ./server:/app
    environment:
      - MODEL_API_URL=http://model_service:5001
    command: npm start

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development

  model_service:
    build:
      context: ./model
      dockerfile: Dockerfile
    volumes:
      - ./model:/app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
